nodeLinker: node-modules

# Suppress peer dependency warnings for known compatible packages
packageExtensions:
  '@solana-mobile/wallet-adapter-mobile@*':
    peerDependenciesMeta:
      react-native:
        optional: true
  '@solana-mobile/mobile-wallet-adapter-protocol@*':
    peerDependenciesMeta:
      react-native:
        optional: true
  '@solana/codecs-strings@*':
    peerDependenciesMeta:
      fastestsmallesttextencoderdecoder:
        optional: true
